[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'cd backend && npm ci --include=dev'
]

[phases.build]
cmds = [
  'npm run build',
  'cd backend && npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'