[build]
builder = "nixpacks"

[deploy]
staticPublishPath = "dist"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_VERSION = "20"

[env]
# Frontend Environment Variables for Railway
VITE_API_BASE_URL = "${{BACKEND_URL}}/api"
VITE_BACKEND_PYTHON_URL = "${{BACKEND_URL}}"
VITE_BACKEND_NODE_URL = "${{BACKEND_URL}}"
VITE_FRONTEND_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Health Monitoring
VITE_HEALTH_CHECK_INTERVAL = "30000"
VITE_HEALTH_TIMEOUT = "5000"

# Build configuration
NODE_ENV = "production"