# Render.com deployment configuration
# Visit render.com and create a new "Blueprint" using this file

services:
  # Backend API
  - type: web
    name: household-services-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: starter
    branch: main
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: household-services-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://household-services-frontend.onrender.com
    healthCheckPath: /ping

  # Frontend (Static Site)
  - type: web
    name: household-services-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://household-services-api.onrender.com

databases:
  - name: household-services-db
    databaseName: household_services
    plan: starter
    region: oregon