# Fly.io deployment configuration
app = "household-services-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  args = { BUILDKIT_INLINE_CACHE = "1" }

[env]
  ENVIRONMENT = "production"
  DEBUG = "false"
  LOG_LEVEL = "INFO"
  HOST = "0.0.0.0"
  SECRET_KEY = "change-this-in-production-fly-secret-key"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    interval = 30000
    timeout = 10000
    grace_period = "30s"
    method = "GET"
    path = "/ping"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "immediate"

# PostgreSQL will be added separately via: fly postgres create