[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

[env]
# Minimal config for Railway free tier
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
HOST = "0.0.0.0"

# Disable database connection during startup for testing
SKIP_DB_CONNECTION = "true"

# Basic auth config
SECRET_KEY = "railway-temp-secret-change-later"
ALGORITHM = "HS256"

# CORS for your Vercel frontend
ALLOWED_ORIGINS = "https://happyhome-zeta.vercel.app"
ALLOWED_METHODS = "GET,POST,PUT,DELETE,OPTIONS"
ALLOWED_HEADERS = "*"

# App info
APP_NAME = "Happy Homes Services API"
APP_VERSION = "1.0.0"
SHOW_DOCS = "true"