[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# FastAPI Configuration - Railway Free Tier Optimized
ENVIRONMENT = "production"
DEBUG = "false" 
LOG_LEVEL = "INFO"
HOST = "0.0.0.0"

# Database will be provided by Railway PostgreSQL service
# DATABASE_URL will be automatically set by Railway

# Security - Use Railway's secret management
SECRET_KEY = "railway-secret-key-change-this-to-random-value"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"

# CORS - Will be updated with your Vercel domain
ALLOWED_ORIGINS = "https://your-frontend.vercel.app"
ALLOWED_METHODS = "GET,POST,PUT,DELETE,OPTIONS,PATCH"
ALLOWED_HEADERS = "*"

# App Configuration
APP_NAME = "Happy Homes Services API"
APP_VERSION = "1.0.0"
SHOW_DOCS = "true"