[build]
builder = "nixpacks"
buildCommand = "pip install fastapi uvicorn"
startCommand = "cd /app && python3 main_simple.py"

[deploy]
# Disable health check temporarily to debug Railway deployment
# healthcheckPath = "/health"
# healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1

[build.env]
PYTHON_VERSION = "3.11"

[env]
# FastAPI Configuration
HOST = "0.0.0.0"
ENVIRONMENT = "production" 
DEBUG = "false"
RELOAD = "false"
LOG_LEVEL = "INFO"

# Database will be provided by Railway PostgreSQL service
# DATABASE_URL will be automatically set by Railway
# If no DATABASE_URL is provided, the application will fail with a clear error

# Security - Generate a secure key for Railway
SECRET_KEY = "railway-secret-key-abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_DAYS = "7"

# CORS - Updated for Railway deployment
ALLOWED_ORIGINS = "https://happyhome-zeta.vercel.app"
ALLOWED_METHODS = "GET,POST,PUT,DELETE,OPTIONS,PATCH"
ALLOWED_HEADERS = "*"

# Ultra-simple deployment - no database, no complex dependencies

# App Configuration
APP_NAME = "Happy Homes Services API"
APP_VERSION = "1.0.0"
SHOW_DOCS = "true"

# File Upload
MAX_FILE_SIZE = "10485760"
UPLOAD_DIR = "/app/uploads"

# Cache and Session
CACHE_TTL = "3600"

# Rate Limiting
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "60"