#!/bin/bash

# Script to create all required subcategory image folders
# Creates folders based on the database structure

BASE_DIR="/Users/supanda/Desktop/backup-22-25/AI/claude/household-services/public/images/subcategories"

echo "🎨 Creating image folders for all subcategories..."
echo "================================================"

# Plumbing Category
echo "📁 Creating Plumbing subcategory folders..."
mkdir -p "$BASE_DIR/plumbing/bath-fittings"
mkdir -p "$BASE_DIR/plumbing/basin-sink"
mkdir -p "$BASE_DIR/plumbing/toilet-classic"
mkdir -p "$BASE_DIR/plumbing/toilet-premium"
mkdir -p "$BASE_DIR/plumbing/water-tank"
mkdir -p "$BASE_DIR/plumbing/pipes"
mkdir -p "$BASE_DIR/plumbing/grouting"
mkdir -p "$BASE_DIR/plumbing/others"
# Electrical Category
echo "📁 Creating Electrical subcategory folders..."
mkdir -p "$BASE_DIR/electrical/wiring"
mkdir -p "$BASE_DIR/electrical/appliance-repair"
mkdir -p "$BASE_DIR/electrical/switches-sockets"
mkdir -p "$BASE_DIR/electrical/fans"
mkdir -p "$BASE_DIR/electrical/lighting"
mkdir -p "$BASE_DIR/electrical/safety-check"
mkdir -p "$BASE_DIR/electrical/others"
mkdir -p "$BASE_DIR/electrical/safety-check"
# Cleaning Category
echo "📁 Creating Cleaning subcategory folders..."
mkdir -p "$BASE_DIR/cleaning/bathroom-cleaning"
mkdir -p "$BASE_DIR/cleaning/ac-cleaning"
mkdir -p "$BASE_DIR/cleaning/water-tank-cleaning"
mkdir -p "$BASE_DIR/cleaning/car-wash"
mkdir -p "$BASE_DIR/cleaning/septic-tank"
mkdir -p "$BASE_DIR/cleaning/water-purifier"
mkdir -p "$BASE_DIR/cleaning/others"
# Call A Service Category
echo "📁 Creating Call A Service subcategory folders..."
mkdir -p "$BASE_DIR/call-a-service/courier"
mkdir -p "$BASE_DIR/call-a-service/cab-booking"
mkdir -p "$BASE_DIR/call-a-service/vehicle-breakdown"
mkdir -p "$BASE_DIR/call-a-service/photographer"
mkdir -p "$BASE_DIR/call-a-service/others"
mkdir -p "$BASE_DIR/call-a-service/vehicle-breakdown"
# Finance & Insurance Category
echo "📁 Creating Finance & Insurance subcategory folders..."
mkdir -p "$BASE_DIR/finance-insurance/gst-registration"
mkdir -p "$BASE_DIR/finance-insurance/pan-card"
mkdir -p "$BASE_DIR/finance-insurance/itr-filing"
mkdir -p "$BASE_DIR/finance-insurance/stamp-paper"
mkdir -p "$BASE_DIR/finance-insurance/others"
# Personal Care Category
echo "📁 Creating Personal Care subcategory folders..."
mkdir -p "$BASE_DIR/personal-care/medicine-delivery"
mkdir -p "$BASE_DIR/personal-care/salon-home"
mkdir -p "$BASE_DIR/personal-care/health-checkup"
mkdir -p "$BASE_DIR/personal-care/others"rs..."
# Civil Work Category
echo "📁 Creating Civil Work subcategory folders..."
mkdir -p "$BASE_DIR/civil-work/painting"
mkdir -p "$BASE_DIR/civil-work/tile-work"
mkdir -p "$BASE_DIR/civil-work/home-repairs"
mkdir -p "$BASE_DIR/civil-work/others"
echo "📁 Creating Civil Work subcategory folders..."
mkdir -p "$BASE_DIR/civil-work/painting"
mkdir -p "$BASE_DIR/civil-work/tile-work"
echo "📊 Folder Summary:"
echo "=================="
echo "Plumbing:           8 folders (7 services + others for PDFs)"
echo "Electrical:         7 folders (6 services + others for PDFs)"
echo "Cleaning:           7 folders (6 services + others for PDFs)"
echo "Call A Service:     5 folders (4 services + others for PDFs)"
echo "Finance Insurance:  5 folders (4 services + others for PDFs)"
echo "Personal Care:      4 folders (3 services + others for PDFs)"
echo "Civil Work:         4 folders (3 services + others for PDFs)"
echo "=================="
echo "Total:             40 folders (32 service folders + 7 'others' for PDFs)"
echo "Finance Insurance:  4 subcategories"
echo "Personal Care:      3 subcategories"
echo "Civil Work:         3 subcategories"
echo ""
echo "💡 Recommended images per subcategory: 4-5 images"
echo "📏 Image format: JPG or PNG, optimized for web"
echo "🎯 Naming convention: {service-name}-{number}.jpg"
echo ""
echo "📄 'others' folders: For PDF files and documents"
echo "   - Brochures, price lists, catalogs"
echo "   - Service agreements, terms & conditions"
echo "   - Technical specifications"
echo ""BASE_DIR"
echo ""
echo "💡 Recommended images per subcategory: 4-5 images"
echo "📏 Image format: JPG or PNG, optimized for web"
echo "🎯 Naming convention: {service-name}-{number}.jpg"
echo ""
